<?php

namespace Database\Seeders;

use App\Models\Support;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class DemoDataSupportSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Start Sumber Data Agus Susanto
        Support::create([
            'parent_id'             => null,
            'nik'                   => '6403052808810001',
            'nama'                  => 'Agus Susanto',
            'alamat'                => 'Jl. Cempaka IV',
            'rt'                    => '3',
            'kabupaten_id'          => 1,
            'kecamatan_id'          => 12,
            'kelurahan_id'          => 104,
            'scanktp'               => null,
            'nohp'                  => '085392019252',
            'keterangan'            => null,
            'rating'                => 5,
            'location_id'           => null,
            'participant_id'        => 1,
            'user_id'               => 1,
        ]);
        Support::create([
            'parent_id'             => null,
            'nik'                   => '6403050307930003',
            'nama'                  => 'Fatrisk',
            'alamat'                => 'Jl. Kelay',
            'rt'                    => '5',
            'kabupaten_id'          => 1,
            'kecamatan_id'          => 12,
            'kelurahan_id'          => 104,
            'scanktp'               => null,
            'nohp'                  => '085374419027',
            'keterangan'            => null,
            'rating'                => 5,
            'location_id'           => null,
            'participant_id'        => 1,
            'user_id'               => 1,
        ]);
        Support::create([
            'parent_id'             => null,
            'nik'                   => '6403050307930004',
            'nama'                  => 'Apriansyah',
            'alamat'                => 'Jl. Mawar',
            'rt'                    => '5',
            'kabupaten_id'          => 1,
            'kecamatan_id'          => 12,
            'kelurahan_id'          => 104,
            'scanktp'               => null,
            'nohp'                  => '085374419027',
            'keterangan'            => null,
            'rating'                => 5,
            'location_id'           => null,
            'participant_id'        => 1,
            'user_id'               => 1,
        ]);
        Support::create([
            'parent_id'             => null,
            'nik'                   => '6403050307930002',
            'nama'                  => 'Ali',
            'alamat'                => 'Jl. Dermaga',
            'rt'                    => '5',
            'kabupaten_id'          => 1,
            'kecamatan_id'          => 12,
            'kelurahan_id'          => 104,
            'scanktp'               => null,
            'nohp'                  => '082153439712',
            'keterangan'            => null,
            'rating'                => 5,
            'location_id'           => null,
            'participant_id'        => 1,
            'user_id'               => 1,
        ]);
        Support::create([
            'parent_id'             => null,
            'nik'                   => '6403050307930006',
            'nama'                  => 'Brayen',
            'alamat'                => 'Jl. Durian 1',
            'rt'                    => '3',
            'kabupaten_id'          => 1,
            'kecamatan_id'          => 12,
            'kelurahan_id'          => 104,
            'scanktp'               => null,
            'nohp'                  => '081245459312',
            'keterangan'            => null,
            'rating'                => 5,
            'location_id'           => null,
            'participant_id'        => 1,
            'user_id'               => 1,
        ]);
        Support::create([
            'parent_id'             => null,
            'nik'                   => '6403050307930007',
            'nama'                  => 'Aco',
            'alamat'                => 'Jl. Sambaliung',
            'rt'                    => '6',
            'kabupaten_id'          => 1,
            'kecamatan_id'          => 12,
            'kelurahan_id'          => 104,
            'scanktp'               => null,
            'nohp'                  => '082195419053',
            'keterangan'            => null,
            'rating'                => 5,
            'location_id'           => null,
            'participant_id'        => 1,
            'user_id'               => 1,
        ]);
        // End Sumber Data Agus Susanto

        // Start Sumber Data Puyan
        Support::create([
            'parent_id'             => null,
            'nik'                   => '6477268100010001',
            'nama'                  => 'Abas',
            'alamat'                => 'Jl. Manggis',
            'rt'                    => '2',
            'kabupaten_id'          => 1,
            'kecamatan_id'          => 8,
            'kelurahan_id'          => 62,
            'scanktp'               => null,
            'nohp'                  => '082264810000',
            'keterangan'            => null,
            'rating'                => 5,
            'location_id'           => null,
            'participant_id'        => 2,
            'user_id'               => 1,
        ]);
        Support::create([
            'parent_id'             => null,
            'nik'                   => '6403510021500008',
            'nama'                  => 'Udin',
            'alamat'                => 'Jl. Mawar',
            'rt'                    => '3',
            'kabupaten_id'          => 1,
            'kecamatan_id'          => 8,
            'kelurahan_id'          => 62,
            'scanktp'               => null,
            'nohp'                  => '0813000555211',
            'keterangan'            => null,
            'rating'                => 5,
            'location_id'           => null,
            'participant_id'        => 2,
            'user_id'               => 1,
        ]);
        Support::create([
            'parent_id'             => null,
            'nik'                   => '6403520041500002',
            'nama'                  => 'Rahman',
            'alamat'                => 'Jl. Melati',
            'rt'                    => '1',
            'kabupaten_id'          => 1,
            'kecamatan_id'          => 8,
            'kelurahan_id'          => 62,
            'scanktp'               => null,
            'nohp'                  => '0813000166222',
            'keterangan'            => null,
            'rating'                => 5,
            'location_id'           => null,
            'participant_id'        => 2,
            'user_id'               => 1,
        ]);
        Support::create([
            'parent_id'             => null,
            'nik'                   => '6403520041600003',
            'nama'                  => 'Usman',
            'alamat'                => 'Jl. Kenanga',
            'rt'                    => '9',
            'kabupaten_id'          => 1,
            'kecamatan_id'          => 12,
            'kelurahan_id'          => 104,
            'scanktp'               => null,
            'nohp'                  => '081255500667',
            'keterangan'            => null,
            'rating'                => 5,
            'location_id'           => null,
            'participant_id'        => 2,
            'user_id'               => 1,
        ]);
        Support::create([
            'parent_id'             => null,
            'nik'                   => '6403020500000008',
            'nama'                  => 'Bagir',
            'alamat'                => 'Jl. Kamboja',
            'rt'                    => '15',
            'kabupaten_id'          => 1,
            'kecamatan_id'          => 12,
            'kelurahan_id'          => 104,
            'scanktp'               => null,
            'nohp'                  => '081300004255',
            'keterangan'            => null,
            'rating'                => 5,
            'location_id'           => null,
            'participant_id'        => 2,
            'user_id'               => 1,
        ]);
        // End Sumber Data Puyan

        // Start Sumber Data Aco
        Support::create([
            'parent_id'             => null,
            'nik'                   => '6555500000002182',
            'nama'                  => 'Nanang',
            'alamat'                => 'Jl. Pahlawan',
            'rt'                    => '1',
            'kabupaten_id'          => 1,
            'kecamatan_id'          => 8,
            'kelurahan_id'          => 65,
            'scanktp'               => null,
            'nohp'                  => '081535123456',
            'keterangan'            => null,
            'rating'                => 5,
            'location_id'           => null,
            'participant_id'        => 3,
            'user_id'               => 1,
        ]);
        Support::create([
            'parent_id'             => null,
            'nik'                   => '6402315568000001',
            'nama'                  => 'Boboy',
            'alamat'                => 'Jl. Bayangkara',
            'rt'                    => '3',
            'kabupaten_id'          => 1,
            'kecamatan_id'          => 8,
            'kelurahan_id'          => 65,
            'scanktp'               => null,
            'nohp'                  => '081222334455',
            'keterangan'            => null,
            'rating'                => 5,
            'location_id'           => null,
            'participant_id'        => 3,
            'user_id'               => 1,
        ]);
        Support::create([
            'parent_id'             => null,
            'nik'                   => '6402516688000001',
            'nama'                  => 'Zaki',
            'alamat'                => 'Jl. MT. Haryono',
            'rt'                    => '2',
            'kabupaten_id'          => 1,
            'kecamatan_id'          => 8,
            'kelurahan_id'          => 65,
            'scanktp'               => null,
            'nohp'                  => '081341454647',
            'keterangan'            => null,
            'rating'                => 5,
            'location_id'           => null,
            'participant_id'        => 3,
            'user_id'               => 1,
        ]);
        Support::create([
            'parent_id'             => null,
            'nik'                   => '6402314466000001',
            'nama'                  => 'Wendy',
            'alamat'                => 'Jl. MT. Haryono',
            'rt'                    => '2',
            'kabupaten_id'          => 1,
            'kecamatan_id'          => 8,
            'kelurahan_id'          => 65,
            'scanktp'               => null,
            'nohp'                  => '081245678910',
            'keterangan'            => null,
            'rating'                => 5,
            'location_id'           => null,
            'participant_id'        => 3,
            'user_id'               => 1,
        ]);
        Support::create([
            'parent_id'             => null,
            'nik'                   => '64031214150000002',
            'nama'                  => 'Wawan',
            'alamat'                => 'Jl. Cempaka',
            'rt'                    => '1',
            'kabupaten_id'          => 1,
            'kecamatan_id'          => 8,
            'kelurahan_id'          => 65,
            'scanktp'               => null,
            'nohp'                  => '081521314151',
            'keterangan'            => null,
            'rating'                => 5,
            'location_id'           => null,
            'participant_id'        => 3,
            'user_id'               => 1,
        ]);
        // End Sumber Data Aco
    }
}
